macos_task:
  name: macos-arm64
  macos_instance:
    image: ghcr.io/cirruslabs/macos-sonoma-base:latest
  env:
    PATH: ${CIRRUS_WORKING_DIR}/venv/bin:${CIRRUS_WORKING_DIR}/pythons/cp38-cp38/bin:${CIRRUS_WORKING_DIR}/pythons/cp39-cp39/bin:${CIRRUS_WORKING_DIR}/pythons/cp310-cp310/bin:${CIRRUS_WORKING_DIR}/pythons/cp311-cp311/bin:${PATH}
  setup_pythons_script: python3 -u docker/install-pythons --dest pythons
  setup_venv_script:
    python3 -um venv venv && pip install -r docker/requirements.txt
  script:
    - brew install go@1.20
  artifacts:
    path: dist/*
