repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: debug-statements
    -   id: name-tests-test
-   repo: local
    hooks:
    -   id: format-packages-ini
        name: format packages.ini
        language: python
        entry: .venv/bin/python -m format_ini
        files: ^packages\.ini$

    - id: ruff-check
      name: ruff check
      entry: .venv/bin/ruff check --fix
      language: system
      types: [python]

    - id: ruff-format
      name: ruff format
      entry: .venv/bin/ruff format
      language: system
      types: [python]

    - id: mypy
      name: mypy
      entry: .venv/bin/mypy
      language: system
      types: [python]
      require_serial: true
