#!/usr/bin/env python3
from __future__ import annotations

import argparse
import os.path
import subprocess
import tempfile


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("crc32c_rev")
    parser.add_argument("prefix")
    args = parser.parse_args()

    with tempfile.TemporaryDirectory() as tmpdir:
        print("cloning crc32c...")
        subprocess.check_call(
            (
                "git",
                "clone",
                "--quiet",
                "https://github.com/google/crc32c",
                tmpdir,
            ),
        )
        subprocess.check_call(
            ("git", "-C", tmpdir, "checkout", "--quiet", args.crc32c_rev)
        )

        print("checking out submodules...")
        subprocess.check_call(
            (
                "git",
                "-C",
                tmpdir,
                "submodule",
                "update",
                "--quiet",
                "--init",
                "--recursive",
                "--depth=1",
            )
        )

        print("building...")
        build_dir = os.path.join(tmpdir, "build")
        os.makedirs(build_dir)
        subprocess.check_call(
            (
                "cmake",
                f"-DCMAKE_INSTALL_PREFIX={args.prefix}",
                "-DCRC32C_BUILD_TESTS=no",
                "-DCRC32C_BUILD_BENCHMARKS=no",
                "-DBUILD_SHARED_LIBS=yes",
                "..",
            ),
            cwd=build_dir,
        )
        subprocess.check_call(("make", "all", "install"), cwd=build_dir)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
