name: auto merge
on:
  pull_request_target:

jobs:
  auto-merge:
    if: github.actor == 'getsentry-bot' && startsWith(github.head_ref, 'craft-')
    runs-on: ubuntu-latest
    steps:
    - run: |
        set -x
        GH_TOKEN=$GHA_TOKEN gh pr review --approve --repo "$GITHUB_REPOSITORY" "$PR"
        GH_TOKEN=$BOT_TOKEN gh pr merge --auto --merge --repo "$GITHUB_REPOSITORY" "$PR"
      env:
        PR: ${{ github.event.number }}
        GHA_TOKEN: ${{ github.token }}
        BOT_TOKEN: ${{ secrets.GH_RELEASE_PAT }}
