name: image
on:
  pull_request:
    paths: [docker/*, pyproject.toml, uv.lock, .github/workflows/image.yml]
  push:
    branches: [main, test-me-*]
    paths: [docker/*, pyproject.toml, uv.lock, .github/workflows/image.yml]

concurrency:
  # serialize runs on the default branch
  group: ${{ github.event_name == 'push' && github.workflow || github.sha }}${{ github.workflow }}

jobs:
  image:
    strategy:
      matrix:
        include:
        - {arch: amd64, os: ubuntu-latest}
        - {arch: arm64, os: ubuntu-24.04-arm}
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
    - name: login
      env:
        GITHUB_ACTOR: ${{ github.actor }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: docker login --username "$GITHUB_ACTOR" --password-stdin ghcr.io <<< "$GITHUB_TOKEN"
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    - name: build
      env:
        ARCH: ${{ matrix.arch }}
        SHA: ${{ github.sha }}
        EVENT_NAME: ${{ github.event_name }}
        REF: ${{ github.ref }}
      run: |
        cp pyproject.toml uv.lock docker/
        docker buildx build \
            --cache-from ghcr.io/getsentry/pypi-manylinux-"$ARCH"-ci:latest \
            --cache-to type=inline \
            --platform linux/"$ARCH" \
            --tag ghcr.io/getsentry/pypi-manylinux-"$ARCH"-ci:"$SHA" \
            --tag ghcr.io/getsentry/pypi-manylinux-"$ARCH"-ci:latest \
            $( [ "$EVENT_NAME" = "push" ] && [ "$REF" = "refs/heads/main" ] && echo "--push" || echo "" ) \
            docker
