name: image
on:
  pull_request:
    paths: [docker/*, .github/workflows/image.yml]
  push:
    branches: [main, test-me-*]
    paths: [docker/*, .github/workflows/image.yml]

concurrency:
  # serialize runs on the default branch
  group: ${{ github.event_name == 'push' && github.workflow || github.sha }}${{ github.workflow }}

jobs:
  image:
    strategy:
      matrix:
        include:
        - {arch: amd64, os: ubuntu-latest}
        - {arch: arm64, os: ubuntu-24.04-arm}
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: login
      run: docker login --username '${{ github.actor }}' --password-stdin ghcr.io <<< '${{ secrets.GITHUB_TOKEN }}'
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    - name: build
      run: |
        docker buildx build \
            --cache-from ghcr.io/getsentry/pypi-manylinux-${{ matrix.arch }}-ci:latest \
            --cache-to type=inline \
            --platform linux/${{ matrix.arch }} \
            --tag ghcr.io/getsentry/pypi-manylinux-${{ matrix.arch }}-ci:${{ github.sha }} \
            --tag ghcr.io/getsentry/pypi-manylinux-${{ matrix.arch }}-ci:latest \
            ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && '--push' || '' }} \
            docker
