name: test
on:
  pull_request:
  push:
    branches: [main, test-me-*]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: astral-sh/setup-uv@e06108dd0aef18192324c70427afc47652e63a82 # v7.5.0
    - run: uv sync
    - run: uv run coverage erase
    - run: uv run coverage run -m pytest tests
    - run: uv run coverage report
